// <auto-generated />
using System;
using AIVES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIVES.Data.Migrations
{
    [DbContext(typeof(AIVESDbContext))]
    partial class AIVESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIVES.Data.Entities.AIScoreSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("MissingInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuggestedScore")
                        .HasColumnType("int");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId")
                        .IsUnique();

                    b.ToTable("AIScoreSuggestions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AIVES.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AIVES.Data.Entities.CourseMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseMaterials");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamParticipants");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerTimeSeconds")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MainQuestionsCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxFollowUpsPerQuestion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TimePerStudentMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("InterviewSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviousQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("InterviewSessionId");

                    b.HasIndex("PreviousQuestionId");

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamParticipantId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExamParticipantId")
                        .IsUnique();

                    b.HasIndex("ExamSessionId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.LecturerEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalScore")
                        .HasColumnType("int");

                    b.Property<int>("InterviewQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("LecturerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId")
                        .IsUnique();

                    b.HasIndex("LecturerId");

                    b.ToTable("LecturerEvaluations");
                });

            modelBuilder.Entity("AIVES.Data.Entities.MaterialChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialChunks");
                });

            modelBuilder.Entity("AIVES.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ReferenceMaterial")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("RubricId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RubricId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.QuestionRubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("QuestionRubrics");
                });

            modelBuilder.Entity("AIVES.Data.Entities.QuestionTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTopics");
                });

            modelBuilder.Entity("AIVES.Data.Entities.RubricCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("RubricId")
                        .HasColumnType("int");

                    b.Property<string>("ScoringGuidance")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("AIVES.Data.Entities.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("InterviewQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SpeechDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("AIVES.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIVES.Data.Entities.AIScoreSuggestion", b =>
                {
                    b.HasOne("AIVES.Data.Entities.InterviewQuestion", "InterviewQuestion")
                        .WithOne("ScoreSuggestion")
                        .HasForeignKey("AIVES.Data.Entities.AIScoreSuggestion", "InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewQuestion");
                });

            modelBuilder.Entity("AIVES.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("AIVES.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIVES.Data.Entities.CourseMaterial", b =>
                {
                    b.HasOne("AIVES.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamParticipant", b =>
                {
                    b.HasOne("AIVES.Data.Entities.ExamSession", "ExamSession")
                        .WithMany("Participants")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.User", "Student")
                        .WithMany("Participants")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamQuestion", b =>
                {
                    b.HasOne("AIVES.Data.Entities.ExamSession", "ExamSession")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamSession", b =>
                {
                    b.HasOne("AIVES.Data.Entities.Course", "Course")
                        .WithMany("ExamSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewQuestion", b =>
                {
                    b.HasOne("AIVES.Data.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("InterviewQuestions")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.InterviewSession", null)
                        .WithMany("Questions")
                        .HasForeignKey("InterviewSessionId");

                    b.HasOne("AIVES.Data.Entities.InterviewQuestion", "PreviousQuestion")
                        .WithMany()
                        .HasForeignKey("PreviousQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExamQuestion");

                    b.Navigation("PreviousQuestion");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewSession", b =>
                {
                    b.HasOne("AIVES.Data.Entities.ExamParticipant", "ExamParticipant")
                        .WithOne("InterviewSession")
                        .HasForeignKey("AIVES.Data.Entities.InterviewSession", "ExamParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.ExamSession", null)
                        .WithMany("InterviewSessions")
                        .HasForeignKey("ExamSessionId");

                    b.Navigation("ExamParticipant");
                });

            modelBuilder.Entity("AIVES.Data.Entities.LecturerEvaluation", b =>
                {
                    b.HasOne("AIVES.Data.Entities.InterviewQuestion", "InterviewQuestion")
                        .WithOne()
                        .HasForeignKey("AIVES.Data.Entities.LecturerEvaluation", "InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.User", "Lecturer")
                        .WithMany("LecturerEvaluations")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewQuestion");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("AIVES.Data.Entities.MaterialChunk", b =>
                {
                    b.HasOne("AIVES.Data.Entities.CourseMaterial", "Material")
                        .WithMany("Chunks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("AIVES.Data.Entities.Question", b =>
                {
                    b.HasOne("AIVES.Data.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIVES.Data.Entities.QuestionRubric", "Rubric")
                        .WithMany("Questions")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AIVES.Data.Entities.QuestionTopic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Rubric");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AIVES.Data.Entities.RubricCriterion", b =>
                {
                    b.HasOne("AIVES.Data.Entities.QuestionRubric", "Rubric")
                        .WithMany("Criteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("AIVES.Data.Entities.StudentAnswer", b =>
                {
                    b.HasOne("AIVES.Data.Entities.InterviewQuestion", "InterviewQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewQuestion");
                });

            modelBuilder.Entity("AIVES.Data.Entities.User", b =>
                {
                    b.HasOne("AIVES.Data.Entities.Course", "Course")
                        .WithMany("Lecturers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AIVES.Data.Entities.Course", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("Lecturers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.CourseMaterial", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamParticipant", b =>
                {
                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamQuestion", b =>
                {
                    b.Navigation("InterviewQuestions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.ExamSession", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("InterviewSessions");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ScoreSuggestion");
                });

            modelBuilder.Entity("AIVES.Data.Entities.InterviewSession", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.Question", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.QuestionRubric", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.QuestionTopic", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIVES.Data.Entities.User", b =>
                {
                    b.Navigation("LecturerEvaluations");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
